### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sirnano** [clairmont32/VirusTotal-Tools#3]
I had to add "if data is not None:" to the below if statement to handle domains that have a 'response_code' of 0

Hopefully this is useful for others

# open domains file and pass them to the scanning/report reading functions, write results to CSV
try:
    with open(filepath, 'r') as infile:  # keeping the file open because it shouldnt# be opened/modified during reading anyway
        for domain in infile:
            domain = domain.strip('\n')
            delay = DomainScanner(domain)
            data = DomainReportReader(domain, delay)
            with open('results.csv', 'a') as rfile:
                if data is not None:
                    datawriter = csv.writer(rfile, delimiter = ',')
                    datawriter.writerow(data)

**Comment by clairmont32** [comment]
Thanks for letting me know. I'll implement a fix for that scenario.

**Comment by clairmont32** [comment]
added a similar line. please let me know if you have any further issues!
