### ISSUE TITLE
can the VT_Hash_Search.py be modified so it can read a txt file 

### ISSUE THREAD

**Issue by M-Matos** [clairmont32/VirusTotal-Tools#7]
Hi, I have been testing your scripts and they work great, Do you know if the VT_Hash_Search.py can be modified so basically works the same as the domain search. it will be great if I can add a hash.txt file with hashes and get the output in a csv. 

Thanks

**Comment by clairmont32** [comment]
Hey @M-Matos, yeah I can make it take a file for input. I've been sick all week so I likely can get to it next week for you.

**Comment by M-Matos** [comment]
Thanks Clairmont for the fast response, that  will be great.  Hope you get better soon. I have one more request, because of the limitation of the virus total api key,  will it be possible to add more than 1 api key for example 4 that way the  first one will be send with api 1, the second with api 2 and so on. that way it will be a little bit fast when processing multiple IP.  Thanks

**Comment by clairmont32** [comment]
Hi, sorry for the several month delay here. Life's been hectic for me during the fall and likely through the rest of Jan. I haven't forgotten about this.

**Comment by M-Matos** [comment]
Sure no problem I understand. Thanks for everything.
________________________________
